JustForFun.Web/Models/ErrorViewModel.cs
using System;

namespace JustForFun.Web.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JustForFun.Web/ViewModels/Response.cs
using Microsoft.AspNetCore.Mvc;

namespace JustForFun.Web.ViewModels {
    public class Response<T> {
        public int Code { get; set; }
        public string Msg { get; set; }
        public int Count { get; set; }
        public T Data { get; set; }

        public ObjectResult ToObjectResult() => new ObjectResult(this);
    }
}

JustForFun.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using JustForFun.Web.Models;

namespace JustForFun.Web.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

JustForFun.Web/Controllers/NeteaseMusicShuffleController.cs
using System.Collections.Generic;
using System.Linq;
using JustForFun.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using NeteaseMusicShuffle;
using NeteaseMusicShuffle.Models;

namespace JustForFun.Web.Controllers {
    public class NeteaseMusicShuffleController : Controller {
        // GET
        public IActionResult Index() {
            return View();
        }

        public ObjectResult MusicList() {
            return new Response<List<SimpleMusic>> {
                Code = 0,
                Count = NeteaseMusicShuffleData.DataList.Count,
                Data = NeteaseMusicShuffleData.DataList,
                Msg = "ok"
            }.ToObjectResult();
        }

        public IActionResult TraditionalAlgorithm() {
            return View();
        }

        public IActionResult MoreFirstAlgorithm() {
            return View();
        }

        public IActionResult LessFirstAlgorithm() {
            return View();
        }

        public ObjectResult TraditionalNextTurn() {
            var data = NeteaseMusicShuffle.Program.TraditionalAlgorithm.NextTurn();

            return new Response<object> {
                Code = 0,
                Data = new {
                    NeteaseMusicShuffle.Program.TraditionalAlgorithm.CurrentTurn,
                    List = data.Select((item) => new {
                        Title = item.Key,
                        PlayedTimes = item.Value
                    }).ToList()
                }
            }.ToObjectResult();
        }

        public ObjectResult TraditionalCurrentPlay() {
            var playList = NeteaseMusicShuffle.Program.TraditionalAlgorithm.PlayList;

            return new Response<object> {
                Code = 0,
                Data = playList.Select((item) => new {
                    Title = item.Key,
                    PlayedTimes = item.Value
                }).ToList()
            }.ToObjectResult();
        }

        public ObjectResult TraditionalCurrentTurn() {
            return new Response<object> {
                Code = 0,
                Data = new {
                    NeteaseMusicShuffle.Program.TraditionalAlgorithm.CurrentTurn,
                    NeteaseMusicShuffle.Program.TraditionalAlgorithm.EveryTurnMusicCount
                }
            }.ToObjectResult();
        }

        public ObjectResult MoreFirstNextTurn() {
            var data = NeteaseMusicShuffle.Program.MoreFirstAlgorithm.NextTurn();

            return new Response<object> {
                Code = 0,
                Data = new {
                    NeteaseMusicShuffle.Program.MoreFirstAlgorithm.CurrentTurn,
                    List = data.Select((item) => new {
                        Title = item.Key,
                        PlayedTimes = item.Value
                    }).ToList()
                }
            }.ToObjectResult();
        }

        public ObjectResult MoreFirstCurrentPlay() {
            var playList = NeteaseMusicShuffle.Program.MoreFirstAlgorithm.PlayList;

            return new Response<object> {
                Code = 0,
                Data = playList.Select((item) => new {
                    Title = item.Key,
                    PlayedTimes = item.Value
                }).ToList()
            }.ToObjectResult();
        }

        public ObjectResult MoreFirstCurrentTurn() {
            return new Response<object> {
                Code = 0,
                Data = new {
                    NeteaseMusicShuffle.Program.MoreFirstAlgorithm.CurrentTurn,
                    NeteaseMusicShuffle.Program.MoreFirstAlgorithm.EveryTurnMusicCount
                }
            }.ToObjectResult();
        }

        public ObjectResult LessFirstNextTurn() {
            var data = NeteaseMusicShuffle.Program.LessFirstAlgorithm.NextTurn();

            return new Response<object> {
                Code = 0,
                Data = new {
                    NeteaseMusicShuffle.Program.LessFirstAlgorithm.CurrentTurn,
                    List = data.Select((item) => new {
                        Title = item.Key,
                        PlayedTimes = item.Value
                    }).ToList()
                }
            }.ToObjectResult();
        }

        public ObjectResult LessFirstCurrentPlay() {
            var playList = NeteaseMusicShuffle.Program.LessFirstAlgorithm.PlayList;

            return new Response<object> {
                Code = 0,
                Data = playList.Select((item) => new {
                    Title = item.Key,
                    PlayedTimes = item.Value
                }).ToList()
            }.ToObjectResult();
        }

        public ObjectResult LessFirstCurrentTurn() {
            return new Response<object> {
                Code = 0,
                Data = new {
                    NeteaseMusicShuffle.Program.LessFirstAlgorithm.CurrentTurn,
                    NeteaseMusicShuffle.Program.LessFirstAlgorithm.EveryTurnMusicCount
                }
            }.ToObjectResult();
        }
    }
}

JustForFun.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section SideNav {
    <partial name="_SideNav"/>
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

JustForFun.Web/Views/Home/_SideNav.cshtml
@using JustForFun.Web.ToolKits

<div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
        <ul class="layui-nav layui-nav-tree" lay-filter="test">
            <li class="layui-nav-item @RazorHelper.SideNavHighlight(ViewContext, "Index")">
                <a asp-controller="Home" asp-action="Index">总览</a>
            </li>
        </ul>
    </div>
</div>

JustForFun.Web/Views/NeteaseMusicShuffle/Index.cshtml
@{
    ViewData["title"] = "网易云随机播放算法优化";
}

@section SideNav {
    <partial name="_SideNav"/>
}


<fieldset class="layui-elem-field layui-field-title">
    <legend>歌曲列表</legend>
</fieldset>

<table class="layui-hide" id="musicList"></table>


@section Scripts {
    <script src="~/js/NeteaseMusicShuffle/index.js"></script>
}

JustForFun.Web/Views/NeteaseMusicShuffle/LessFirstAlgorithm.cshtml
@{
    ViewData["title"] = "少次优先算法";
}

@section SideNav {
    <partial name="_SideNav"/>
}

<blockquote class="layui-elem-quote">
    少次优先算法
</blockquote>

<fieldset class="layui-elem-field layui-field-title">
    <legend>
        播放列表，当前第<span id="current-turn">0</span>轮，已经播放<span id="total-play">0</span>首歌曲
    </legend>
</fieldset>

<div id="chart" style="width: 100%;height: 300px;"></div>

<div class="layui-row">
    <div class="layui-col-xs1">
        <button type="button" class="layui-btn layui-btn-disabled" style="width: 100%;">上一轮</button>
    </div>
    <div class="layui-col-xs1 layui-col-xs-offset10">
        <button type="button" class="layui-btn" id="next-turn" style="width: 100%;">下一轮</button>
    </div>
</div>

<div class="layui-row">
    <div class="layui-col-xs5">
        <table class="layui-hide" id="currentPlay"></table>
    </div>
    <div class="layui-col-xs5 layui-col-xs-offset2">
        <table class="layui-hide" id="currentTurn"></table>
    </div>
</div>


@section Scripts {
    <script src="~/lib/echarts/dist/echarts.min.js"></script>
    <script src="~/js/NeteaseMusicShuffle/lessFirstAlgorithm.js"></script>
}

JustForFun.Web/Views/NeteaseMusicShuffle/MoreFirstAlgorithm.cshtml
@{
    ViewData["title"] = "多次优先算法";
}

@section SideNav {
    <partial name="_SideNav"/>
}

<blockquote class="layui-elem-quote">
    多次优先算法
</blockquote>

<fieldset class="layui-elem-field layui-field-title">
    <legend>
        播放列表，当前第<span id="current-turn">0</span>轮，已经播放<span id="total-play">0</span>首歌曲
    </legend>
</fieldset>

<div id="chart" style="width: 100%;height: 300px;"></div>

<div class="layui-row">
    <div class="layui-col-xs1">
        <button type="button" class="layui-btn layui-btn-disabled" style="width: 100%;">上一轮</button>
    </div>
    <div class="layui-col-xs1 layui-col-xs-offset10">
        <button type="button" class="layui-btn" id="next-turn" style="width: 100%;">下一轮</button>
    </div>
</div>

<div class="layui-row">
    <div class="layui-col-xs5">
        <table class="layui-hide" id="currentPlay"></table>
    </div>
    <div class="layui-col-xs5 layui-col-xs-offset2">
        <table class="layui-hide" id="currentTurn"></table>
    </div>
</div>


@section Scripts {
    <script src="~/lib/echarts/dist/echarts.min.js"></script>
    <script src="~/js/NeteaseMusicShuffle/moreFirstAlgorithm.js"></script>
}

JustForFun.Web/Views/NeteaseMusicShuffle/TraditionalAlgorithm.cshtml
@{
    ViewData["title"] = "传统算法";
}

@section SideNav {
    <partial name="_SideNav"/>
}

<blockquote class="layui-elem-quote">
    常规的随机播放方式，每次播放随机取一首歌，在听歌量比较少的情况下，分布很不均匀。
</blockquote>

<fieldset class="layui-elem-field layui-field-title">
    <legend>
        播放列表，当前第<span id="current-turn">0</span>轮，已经播放<span id="total-play">0</span>首歌曲
    </legend>
</fieldset>

<div id="chart" style="width: 100%;height: 300px;"></div>

<div class="layui-row">
    <div class="layui-col-xs1">
        <button type="button" class="layui-btn layui-btn-disabled" style="width: 100%;">上一轮</button>
    </div>
    <div class="layui-col-xs1 layui-col-xs-offset10">
        <button type="button" class="layui-btn" id="next-turn" style="width: 100%;">下一轮</button>
    </div>
</div>

<div class="layui-row">
    <div class="layui-col-xs5">
        <table class="layui-hide" id="currentPlay"></table>
    </div>
    <div class="layui-col-xs5 layui-col-xs-offset2">
        <table class="layui-hide" id="currentTurn"></table>
    </div>
</div>


@section Scripts {
    <script src="~/lib/echarts/dist/echarts.min.js"></script>
    <script src="~/js/NeteaseMusicShuffle/traditionalAlgorithm.js"></script>
}

JustForFun.Web/Views/NeteaseMusicShuffle/_SideNav.cshtml
@using JustForFun.Web.ToolKits

<div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
        <ul class="layui-nav layui-nav-tree" lay-filter="test">
            <li class="layui-nav-item @RazorHelper.SideNavHighlight(ViewContext, "Index")">
                <a asp-controller="NeteaseMusicShuffle" asp-action="Index">总览</a>
            </li>
            <li class="layui-nav-item @RazorHelper.SideNavHighlight(ViewContext, "TraditionalAlgorithm")">
                <a asp-controller="NeteaseMusicShuffle" asp-action="TraditionalAlgorithm">常规算法</a>
            </li>

            <li class="layui-nav-item @RazorHelper.SideNavHighlight(ViewContext, "MoreFirstAlgorithm")">
                <a asp-controller="NeteaseMusicShuffle" asp-action="MoreFirstAlgorithm">多次优先算法</a>
            </li>
            <li class="layui-nav-item @RazorHelper.SideNavHighlight(ViewContext, "LessFirstAlgorithm")">
                <a asp-controller="NeteaseMusicShuffle" asp-action="LessFirstAlgorithm">少次优先算法</a>
            </li>
        </ul>
    </div>
</div>

JustForFun.Web/Views/Shared/_Layout.cshtml
@using JustForFun.Web.ToolKits
@{
}

<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>JustForFun算法可视化平台 - @ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/layui/css/layui.css">
</head>

<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">JustForFun算法可视化平台</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item @RazorHelper.MenuHighlight(ViewContext, "Home")">
                <a asp-controller="Home" asp-action="Index">首页</a>
            </li>
            <li class="layui-nav-item @RazorHelper.MenuHighlight(ViewContext, "NeteaseMusicShuffle")">
                <a asp-controller="NeteaseMusicShuffle" asp-action="Index">网易云随机算法改进</a>
            </li>
            <li class="layui-nav-item">
                <a href="javascript:;">其它</a>
                <dl class="layui-nav-child">
                    <dd>
                        <a href="#" onclick="msgBox('暂未开启')">邮件管理</a>
                    </dd>
                    <dd>
                        <a href="#" onclick="msgBox('暂未开启')">消息管理</a>
                    </dd>
                    <dd>
                        <a href="#" onclick="msgBox('暂未开启')">授权管理</a>
                    </dd>
                </dl>
            </li>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <i class="layui-icon layui-icon-friends"></i>
                    管理员
                </a>
                <dl class="layui-nav-child">
                    <dd>
                        <a href="#" onclick="msgBox('暂未开启')">基本资料</a>
                    </dd>
                    <dd>
                        <a href="#" onclick="msgBox('暂未开启')">安全设置</a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a href="">退出</a>
            </li>
        </ul>
    </div>

    <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
    @RenderSection("SideNav", required: false)

    <div class="layui-body" style="bottom: 0;">
        <!-- 内容主体区域 -->
        <div style="padding: 15px 15px 0 15px;">
            @RenderBody()
        </div>
    </div>

    @* <div class="layui-footer"> *@
    @*     <!-- 底部固定区域 --> *@
    @*     © OneCat 技术支持 *@
    @* </div> *@
</div>

<!-- 引入LayUI -->
<script src="~/lib/layui/layui.js"></script>
<script>
    //JavaScript代码区域
    layui.use('element', function () {
        let element = layui.element;
    });
</script>

<!-- 引入全局js文件 -->
<script src="~/js/site.js"></script>

<!-- 引入jQuery -->
<script src="~/lib/jquery/dist/jquery.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>

</html>